name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          env
          .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m venv env
        .\env\Scripts\activate.bat
        pip install pyqt6 frenpy pyinstaller

    - name: Build with PyInstaller
      run: |
        .\env\Scripts\activate.bat
        pyinstaller main.py --noconfirm --hide-console

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist
